"""Writing Agent — generates research reports and documents.

Responsibilities:
- Generate structured research reports
- Format citations and bibliographies
- Support multiple output formats (Markdown, LaTeX, DOCX)
- Apply templates and styles
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from research_tool.agents.base import AgentResult, BaseAgent


class WritingAgent(BaseAgent):
    """Generates research reports from synthesized findings."""

    name = "writing"
    description = "Generates structured research reports in multiple formats"

    async def execute(self, **kwargs: Any) -> AgentResult:
        """Generate a report."""
        synthesis = kwargs.get("synthesis", {})
        plan = kwargs.get("plan")
        output_format = kwargs.get("output_format", "markdown")

        report_path = await self.generate(synthesis, plan, output_format)
        return AgentResult(
            success=True,
            data={"report_path": str(report_path)},
        )

    async def generate(
        self,
        synthesis: dict[str, Any],
        plan: Any,
        output_format: str = "markdown",
    ) -> Path:
        """Generate a full research report."""
        if output_format == "markdown":
            return self._generate_markdown(synthesis, plan)
        elif output_format == "latex":
            return self._generate_latex(synthesis, plan)
        else:
            return self._generate_markdown(synthesis, plan)

    def _generate_markdown(self, synthesis: dict[str, Any], plan: Any) -> Path:
        """Generate a Markdown report."""
        sections = synthesis.get("sections", [])
        themes = synthesis.get("themes", [])
        summary = synthesis.get("summary", "")
        gaps = synthesis.get("gaps", [])

        lines = [
            f"# Research Report: {plan.query}",
            "",
            f"*Generated by Research Tool | Depth: {plan.depth}*",
            "",
            "---",
            "",
            "## Abstract",
            "",
            summary,
            "",
            "---",
            "",
        ]

        # Generate each section
        for section in sections:
            level = "#" * (section.get("level", 2) + 1)
            lines.append(f"{level} {section['title']}")
            lines.append("")
            lines.append(f"*{section.get('content_outline', '')}*")
            lines.append("")

            # Add findings for this section
            if section.get("findings"):
                lines.append("Key papers in this section:")
                lines.append("")
                for paper_title in section["findings"][:5]:
                    lines.append(f"- {paper_title}")
                lines.append("")

        # Add limitations and future work
        if gaps:
            lines.append("---")
            lines.append("")
            lines.append("## Limitations and Future Work")
            lines.append("")
            for gap in gaps:
                lines.append(f"- {gap}")
            lines.append("")

        # Add bibliography placeholder
        lines.append("---")
        lines.append("")
        lines.append("## Bibliography")
        lines.append("")
        lines.append("*Citations will be added as papers are indexed.*")
        lines.append("")

        # Write to file
        output_dir = Path(plan.query.lower().replace(" ", "-")[:50]) if hasattr(plan, "query") else Path("research-output")
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / "report.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")

        self._log(f"Report written to {report_path}")
        return report_path

    def _generate_latex(self, synthesis: dict[str, Any], plan: Any) -> Path:
        """Generate a LaTeX report."""
        # LaTeX generation follows similar structure but with TeX formatting
        # For now, fall back to markdown
        self._log("LaTeX generation not yet implemented, using Markdown")
        return self._generate_markdown(synthesis, plan)
