"""Writing Agent — LLM-powered research report generation.

Generates structured research reports with LLM-written prose for each section.
Falls back to template-based generation if LLM is unavailable.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any, Optional

from research_tool.agents.base import AgentResult, BaseAgent
from research_tool.agents.prompts import (
    format_abstract_prompt,
    format_limitations_prompt,
    format_section_prompt,
)


class WritingAgent(BaseAgent):
    """Generates research reports from synthesized findings using LLM."""

    name = "writing"
    description = "Generates structured research reports with LLM-written prose"

    async def execute(self, **kwargs: Any) -> AgentResult:
        """Generate a report."""
        synthesis = kwargs.get("synthesis", {})
        plan = kwargs.get("plan")
        output_format = kwargs.get("output_format", "markdown")

        report_path = await self.generate(synthesis, plan, output_format)
        return AgentResult(
            success=True,
            data={"report_path": str(report_path)},
        )

    async def generate(
        self,
        synthesis: dict[str, Any],
        plan: Any,
        output_format: str = "markdown",
    ) -> Path:
        """Generate a full research report."""
        if output_format == "markdown":
            return await self._generate_markdown(synthesis, plan)
        elif output_format == "latex":
            return self._generate_latex(synthesis, plan)
        else:
            return await self._generate_markdown(synthesis, plan)

    async def _generate_markdown(
        self, synthesis: dict[str, Any], plan: Any
    ) -> Path:
        """Generate a Markdown report with LLM-written sections."""
        query = plan.query if hasattr(plan, "query") else str(plan)
        depth = plan.depth if hasattr(plan, "depth") else "standard"
        sections = synthesis.get("sections", [])
        themes = synthesis.get("themes", [])
        summary = synthesis.get("summary", "")
        gaps = synthesis.get("gaps", [])

        lines = [
            f"# Research Report: {query}",
            "",
            f"*Generated by Research Tool | Depth: {depth}*",
            "",
            "---",
            "",
        ]

        # Generate abstract via LLM
        self._log("Generating abstract...")
        abstract_text = await self._write_abstract(synthesis, plan)
        lines.extend(["## Abstract", "", abstract_text, "", "---", ""])

        # Generate each section via LLM (with concurrency limit)
        self._log(f"Generating {len(sections)} sections...")
        semaphore = asyncio.Semaphore(min(self.config.max_concurrent_agents, 3))

        async def _write_section(section: dict[str, Any]) -> tuple[int, str]:
            async with semaphore:
                idx = sections.index(section)
                content = await self._write_section_content(section, synthesis, plan)
                return idx, content

        tasks = [_write_section(s) for s in sections]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Assemble sections in order
        section_contents: dict[int, str] = {}
        for result in results:
            if isinstance(result, Exception):
                self._log(f"Section generation failed: {result}")
                continue
            idx, content = result
            section_contents[idx] = content

        for i, section in enumerate(sections):
            level = "#" * (section.get("level", 2) + 1)
            lines.append(f"{level} {section['title']}")
            lines.append("")
            if i in section_contents:
                lines.append(section_contents[i])
            else:
                # Fallback: outline only
                lines.append(f"*{section.get('content_outline', '')}*")
                if section.get("findings"):
                    lines.append("")
                    for title in section["findings"][:5]:
                        lines.append(f"- {title}")
            lines.append("")

        # Limitations and future work via LLM
        if gaps:
            self._log("Writing limitations section...")
            limitations_text = await self._write_limitations(synthesis, plan)
            lines.extend(["---", "", "## Limitations and Future Work", "", limitations_text, ""])

        # Bibliography
        lines.extend(["---", "", "## Bibliography", ""])
        findings = synthesis.get("sections", [])
        all_papers = set()
        for section in sections:
            for title in section.get("findings", []):
                all_papers.add(title)
        for title in sorted(all_papers):
            lines.append(f"- {title}")

        # Write file
        report_path = Path(plan.project_dir if hasattr(plan, "project_dir") else ".") / "report.md"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text("\n".join(lines), encoding="utf-8")
        self._log(f"Report written to {report_path}")
        return report_path

    # ── LLM section writers ───────────────────────────────────────────────

    async def _write_abstract(
        self, synthesis: dict[str, Any], plan: Any
    ) -> str:
        """Generate abstract via LLM."""
        query = plan.query if hasattr(plan, "query") else str(plan)
        depth = plan.depth if hasattr(plan, "depth") else "standard"

        system, user = format_abstract_prompt(
            query=query,
            depth=depth,
            paper_count=synthesis.get("papers_count", 0),
            themes=synthesis.get("themes", []),
            summary=synthesis.get("summary", ""),
            gaps=synthesis.get("gaps", []),
        )
        result = await self._llm(user, system=system, max_tokens=1024, use_cache=True)
        if result.startswith("[LLM call failed"):
            return self._fallback_abstract(synthesis, plan)
        return result

    async def _write_section_content(
        self,
        section: dict[str, Any],
        synthesis: dict[str, Any],
        plan: Any,
    ) -> str:
        """Generate a single section's content via LLM."""
        query = plan.query if hasattr(plan, "query") else str(plan)

        # Build findings summary for this section
        findings_summary = "\n".join(
            f"- {title}" for title in section.get("findings", [])[:5]
        ) or "No specific papers identified."

        synthesis_notes = f"Consensus: {section.get('consensus', 'N/A')}"
        if section.get("debate"):
            synthesis_notes += f"\nDebate: {section['debate']}"

        system, user = format_section_prompt(
            section=section,
            query=query,
            findings_summary=findings_summary,
            synthesis_notes=synthesis_notes,
        )
        result = await self._llm(user, system=system, max_tokens=2048, use_cache=True)
        if result.startswith("[LLM call failed"):
            return f"*{section.get('content_outline', 'Section content pending.')}*"
        return result

    async def _write_limitations(
        self, synthesis: dict[str, Any], plan: Any
    ) -> str:
        """Generate limitations section via LLM."""
        query = plan.query if hasattr(plan, "query") else str(plan)

        system, user = format_limitations_prompt(
            query=query,
            paper_count=synthesis.get("papers_count", 0),
            gaps=synthesis.get("gaps", []),
            methods=synthesis.get("methodological_trends", "Not specified"),
        )
        result = await self._llm(user, system=system, max_tokens=1024, use_cache=True)
        if result.startswith("[LLM call failed"):
            return "\n".join(f"- {g}" for g in synthesis.get("gaps", []))
        return result

    # ── Fallbacks ─────────────────────────────────────────────────────────

    def _fallback_abstract(
        self, synthesis: dict[str, Any], plan: Any
    ) -> str:
        """Template-based abstract when LLM fails."""
        query = plan.query if hasattr(plan, "query") else str(plan)
        count = synthesis.get("papers_count", 0)
        themes = ", ".join(synthesis.get("themes", [])[:3])
        return (
            f"This report presents a literature review of {count} papers on "
            f"\"{query}.\" The analysis identified major themes including "
            f"{themes}. Key findings and research gaps are discussed."
        )

    def _generate_latex(self, synthesis: dict[str, Any], plan: Any) -> Path:
        """Generate LaTeX report (uses templates, not LLM)."""
        query = plan.query if hasattr(plan, "query") else str(plan)
        sections = synthesis.get("sections", [])

        lines = [
            r"\documentclass[12pt,a4paper]{article}",
            r"\usepackage[utf8]{inputenc}",
            r"\usepackage{hyperref}",
            r"\usepackage{graphicx}",
            r"\usepackage{booktabs}",
            "",
            r"\title{" + query + "}",
            r"\author{Research Tool}",
            r"\date{\today}",
            "",
            r"\begin{document}",
            r"\maketitle",
            "",
            r"\begin{abstract}",
            synthesis.get("summary", ""),
            r"\end{abstract}",
            "",
        ]

        for section in sections:
            lines.append(f"\\section{{{section['title']}}}")
            lines.append(section.get("content_outline", ""))
            lines.append("")

        lines.extend([r"\end{document}", ""])

        report_path = Path(plan.project_dir if hasattr(plan, "project_dir") else ".") / "report.tex"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text("\n".join(lines), encoding="utf-8")
        return report_path
